library(shiny)
library(shinyWidgets)
library(DT)
library(dplyr)
library(readr)
library(ggplot2)
library(cowplot)
source('ui.R', local = TRUE)
source('server.R')
source('global.R')

shinyApp(ui = ui, server = server)